### ISSUE TITLE
.

### ISSUE THREAD

**Issue by ghost** [LoliKingdom/NukeJndiLookupFromLog4j#2]
.

**Comment by Rongmario** [comment]
The java app does exactly that, for the technical illiterate. That's all.

**Comment by Droid-Hai** [comment]
I was wondering if I could ask a question of a slightly different nature? It looks like I'm not technically literate either.

**Comment by Rongmario** [comment]
Ask away.

**Comment by Droid-Hai** [comment]
is it possible to update it to the new version 2.15, just edited the jar

**Comment by Rongmario** [comment]
If you want to update to 2.15, that's possible, but you wouldn't need this tool. You'd just replace the 2.15 jar with your existing version's jar.

**Comment by Droid-Hai** [comment]
as far as I can see, they are there just in one folder, however, I wonder if this will work for things like a forge or a sigot

**Comment by Rongmario** [comment]
If you're using forge, you can use the forge mod instead.

**Comment by Droid-Hai** [comment]
Yes, that's what I was going to do. but how to be a server on spigot. as I already asked, will this work? if we say directly replace the files that are in it, just with new ones. will it fail or will it work well. if so, it would be nice to implement it with a similar program.

**Comment by Rongmario** [comment]
You can use the tool to patch the vulnerability yes, the log4j jar should be in your libraries folder inside of your server folder.

**Comment by Droid-Hai** [comment]
just deleting this file right?

**Comment by Rongmario** [comment]
The JndiLookup class needs removing in the log4j jar, yes. The tool does it for you.

**Comment by Droid-Hai** [comment]
but, I meant, an update for all these things, client/server. instead of deleting the file. I think that's what you need to do. state me if I'm wrong about something or it just sounds stupid

**Comment by Rongmario** [comment]
You won't need to update anything, these libraries mojang uses hardly is updated, but if Mojang prompts an update, you can go ahead as the vulnerability is patched in new versions.

**Comment by Droid-Hai** [comment]
OK. now it's closed
